# Copyright (C) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 9443
  selector:
    app: {{ .Values.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          image: {{ .Values.imageName }}:{{ .Values.imageVersion }}
          resources:
            requests:
              memory: {{ .Values.requestMemory }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
      volumes:
        - name: webhook-certs
          emptyDir: {}
      serviceAccountName: {{ .Values.name }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}-appconfig-defaulter
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
webhooks:
  - name: {{ .Values.name }}-appconfig-defaulter.oracle.com
    clientConfig:
      service:
        name: {{ .Values.name }}
        namespace: {{ .Values.namespace }}
        path: "/appconfig-defaulter"
    rules:
      - apiGroups:
          - core.oam.dev
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - applicationconfigurations
    sideEffects: None
    failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}-ingresstrait-validator
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
webhooks:
  - name: {{ .Values.name }}-ingresstrait-validator.oracle.com
    clientConfig:
      service:
        name: {{ .Values.name }}
        namespace: {{ .Values.namespace }}
        path: "/validate-oam-verrazzano-io-v1alpha1-ingresstrait"
    rules:
      - apiGroups:
          - oam.verrazzano.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresstraits
    sideEffects: None
    failurePolicy: Fail
