# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
name: verrazzano

global:
  imagePullSecrets: []

image:
  pullPolicy: Always
  terminationGracePeriodSeconds: 60

appBinding:
  useSystemVMI: false

elasticSearch:
  nodes:
    master:
      replicas: 3
      requests:
        memory: 1.4Gi
    data:
      replicas: 2
      requests:
        memory: 4.8Gi
    ingest:
      replicas: 1
      requests:
        memory: 2.5Gi

verrazzanoOperator:
  name: verrazzano-operator
  imageName: localhost:5000/verrazzano/verrazzano-operator
  imageVersion: 0.6.0-20201120085322-82bcb1b
  cohMicroImage: localhost:5000/verrazzano/verrazzano-coh-cluster-operator:0.5.0-20201112155855-709d712
  helidonMicroImage: localhost:5000/verrazzano/verrazzano-helidon-app-operator:0.5.0-20201112153844-e0e4790
  wlsMicroImage: localhost:5000/verrazzano/verrazzano-wko-operator:0.5.0-20201112154348-48bbb61
  prometheusPusherImage: localhost:5000/verrazzano/prometheus-pusher:1.0.1-20201016212958-5b64612
  nodeExporterImage: localhost:5000/verrazzano/node-exporter:0.18.1-20201016212926-e3dc9ad
  filebeatImage: localhost:5000/verrazzano/filebeat:6.8.3-20201016212236-05eabe44b
  journalbeatImage: localhost:5000/verrazzano/journalbeat:6.8.3-20201016212623-05eabe44b
  weblogicOperatorImage: oracle/weblogic-kubernetes-operator:3.0.2
  fluentdImage: localhost:5000/verrazzano/fluentd-kubernetes-daemonset:v1.10.4-20201016214205-7f37ac6
  apiServerRealm: verrazzano-system
  RequestMemory: 72Mi
  cohMicroRequestMemory: 28Mi
  helidonMicroRequestMemory: 24Mi
  wlsMicroRequestMemory: 32Mi
  esDataStorageSize: 50Gi
  grafanaRequestMemory: 48Mi
  grafanaDataStorageSize: 50Gi
  prometheusRequestMemory: 128Mi
  prometheusDataStorageSize: 50Gi
  kibanaRequestMemory: 192Mi

monitoringOperator:
  name: verrazzano-monitoring-operator
  imageName: localhost:5000/verrazzano/verrazzano-monitoring-operator
  imageVersion: 0.6.0-20201119214106-c34f49b
  metricsPort: 8090
  defaultSimpleCompReplicas: 1
  defaultPrometheusReplicas: 1
  grafanaImage: container-registry.oracle.com/olcne/grafana:v6.4.4
  prometheusImage: container-registry.oracle.com/olcne/prometheus:v2.13.1
  prometheusInitImage: ghcr.io/oracle/oraclelinux:7-slim
  prometheusGatewayImage: localhost:5000/verrazzano/prometheus-pushgateway:1.2.0-20201016205229-164dd8b
  alertManagerImage: "noimage"
  esWaitTargetVersion: 7.6.1
  esImage: localhost:5000/verrazzano/elasticsearch:7.6.1-20201130145440-5c76ab1
  esWaitImage: localhost:5000/verrazzano/verrazzano-monitoring-instance-eswait:0.6.0-20201119214106-c34f49b
  esInitImage: ghcr.io/oracle/oraclelinux:7.8
  kibanaImage: localhost:5000/verrazzano/kibana:7.6.1-20201130145840-7717e73
  monitoringInstanceApiImage: localhost:5000/verrazzano/verrazzano-monitoring-instance-api:0.5.0-20201112155857-82662f1
  configReloaderImage: localhost:5000/verrazzano/configmap-reload:0.3-20201016205243-4f24a0e
  nodeExporterImage: localhost:5000/verrazzano/node-exporter:0.18.1-20201016212926-e3dc9ad
  RequestMemory: 48Mi

clusterOperator:
  name: verrazzano-cluster-operator
  imageName: localhost:5000/verrazzano/verrazzano-cluster-operator
  imageVersion: 0.5.0-20201113214457-cf62537
  rancherURL:
  rancherUserName:
  rancherPassword:
  rancherHostname:
  RequestMemory: 27Mi

verrazzanoAdmissionController:
  name: verrazzano-validation
  controllerName: verrazzano-admission-controller
  imageName: localhost:5000/verrazzano/verrazzano-admission-controller
  imageVersion: 0.5.0-20201113214810-3312700
  caBundle:
  RequestMemory: 15Mi

# OCI-related values
oci:
  region: ""
  tenancyOcid: ""
  userOcid: ""
  fingerprint: ""
  privateKey: ""
  compartment: ""
  clusterOcid: ""
  objectStore:
    bucketName: ""
    namespace: ""

config:
  envName:
  dnsSuffix: verrazzano.io
  enableMonitoringStorage: true
